# Lighthouse-Badger | GitHub Action
# 
# Description: Generates, adds & updates manually/automatically Lighthouse badges & reports from one/multiple input URL(s) to a selected target repository
# Author: Sitdisch
# Source: https://github.com/myactionway/lighthouse-badger-action
# License: MIT
# Copyright (c) 2021 Sitdisch

name: 'Lighthouse-Badger'
author: 'Sitdisch'
description: "Generates, adds & updates manually/automatically Lighthouse badges & reports from 1,2... input URL(s) to a target repository"
branding:
  icon: bold
  color: purple

inputs:
  urls:
    description: 'URL(s) to be checked'
    required: true
  badges-args:
    description: 'Badges arguments: -b, -l, -o, -r, -s'
    required: true
  results-type:
    description: 'Results type: mobile, desktop or both'
    required: true
  mobile-lighthouse-params:
    description: 'Lighthouse parameters mobile audit'
    required: true
  desktop-lighthouse-params:
    description: 'Lighthouse parameters desktop audit'
    required: true
  user-name:
    description: 'User who should commit'
    required: true
  user-email:
    description: 'User e-mail address'
    required: true
  commit-message:
    description: 'Commit message'
    required: true

runs:
  using: "composite"
  steps:
    - name: Preparatory Tasks
      run: |
        echo 'export RESULTS_PATH=`expr "${{ inputs.badges-args }}" : ".* --\?ou\?t\?p\?u\?t\?-\?p\?a\?t\?h\? \([^ ]*\).*"`' >> ~/lighthouse_badger_env.txt
        echo 'export BADGES_ARGS=$(sed -e "s/ \(\(--output-path\)\|\(-o\)\) \S*//g" <<< "${{ inputs.badges-args }}" )' >> ~/lighthouse_badger_env.txt
        source ~/lighthouse_badger_env.txt
        mkdir -p $RESULTS_PATH
      shell: bash
    - name: Create Mobile Results
      run: |
        if [ ${{ inputs.results-type }} = "both" ] || [ ${{ inputs.results-type }} = "mobile" ]; then
          source ~/lighthouse_badger_env.txt
          cd temp_lighthouse_badges_nested
          export LIGHTHOUSE_BADGES_PARAMS="${{ inputs.mobile-lighthouse-params }}"
          ./src/index.js -u ${{ inputs.urls }} $BADGES_ARGS -o mobile
          cp -r mobile ../$RESULTS_PATH
          cd ..
        fi
      shell: bash
    - name: Create Desktop Results
      run: |
        if [ ${{ inputs.results-type }} = "both" ] || [ ${{ inputs.results-type }} = "desktop" ]; then
          source ~/lighthouse_badger_env.txt
          cd temp_lighthouse_badges_nested
          export LIGHTHOUSE_BADGES_PARAMS="${{ inputs.desktop-lighthouse-params }}"
          ./src/index.js -u ${{ inputs.urls }} $BADGES_ARGS -o desktop
          cp -r desktop ../$RESULTS_PATH
          cd ..
        fi
      shell: bash
    - name: Commit Results
      run: |
        source ~/lighthouse_badger_env.txt
        git config --local user.email ${{ inputs.user-email }}
        git config --local user.name ${{ inputs.user-name }}
        git add $RESULTS_PATH
        git commit -am "${{ inputs.commit-message }}"
        git push
      shell: bash
