# Lighthouse-Badger | GitHub Action
# 
# Description: Generates, adds & updates manually/automatically Lighthouse badges & reports from one/multiple input URL-group(s) to one/multiple target repo(s)/branch(es)
# Author: Sitdisch
# Version: v1.1
# Source: https://github.com/myactionway/lighthouse-badger-action
# License: MIT
# Copyright (c) 2021 Sitdisch

name: 'Lighthouse-Badger'
author: 'Sitdisch'
description: "Generates, adds & updates manually/automatically Lighthouse badges & reports from 1,2... URL(s) to 1,2... repo(s)/branch(es)"
branding:
  icon: bold
  color: white

inputs:
  urls:
    description: 'URL(s) to be checked'
    required: true
  badges-args:
    description: 'Badges arguments: -b, -l, -o, -r, -s'
    required: true
  results-type:
    description: 'Results type: mobile, desktop or both'
    required: true
  mobile-lighthouse-params:
    description: 'Lighthouse parameters mobile audit'
    required: true
  desktop-lighthouse-params:
    description: 'Lighthouse parameters desktop audit'
    required: true
  user-name:
    description: 'User who should commit'
    required: true
  user-email:
    description: 'User e-mail address'
    required: true
  commit-message:
    description: 'Commit message'
    required: true

runs:
  using: "composite"
  steps:
    - run: |
        RESULTS_PATH=`expr "${{ inputs.badges-args }}" : ".* --\?ou\?t\?p\?u\?t\?-\?p\?a\?t\?h\? \([^ ]*\).*"`;
        BADGES_ARGS=$(sed -e "s/ \(\(--output-path\)\|\(-o\)\) \S*//g" <<< "${{ inputs.badges-args }}" );
        mkdir -p $RESULTS_PATH
        cd temp_lighthouse_badges_nested
        if [ ${{ inputs.results-type }} = "both" ]; then
          { export LIGHTHOUSE_BADGES_PARAMS="${{ inputs.mobile-lighthouse-params }}"; ./src/index.js -u ${{ inputs.urls }} $BADGES_ARGS -o $RESULTS_PATH/mobile; cp -r $RESULTS_PATH/mobile ../$RESULTS_PATH; } & 
          { export LIGHTHOUSE_BADGES_PARAMS="${{ inputs.desktop-lighthouse-params }}"; ./src/index.js -u ${{ inputs.urls }} $BADGES_ARGS -o $RESULTS_PATH/desktop; cp -r $RESULTS_PATH/desktop ../$RESULTS_PATH; } &
          wait
        else
          if [ ${{ inputs.results-type }} = "mobile" ]; then
            export LIGHTHOUSE_BADGES_PARAMS="${{ inputs.mobile-lighthouse-params }}"
          else
            export LIGHTHOUSE_BADGES_PARAMS="${{ inputs.desktop-lighthouse-params }}"
          fi
          ./src/index.js -u ${{ inputs.urls }} $BADGES_ARGS -o $RESULTS_PATH/${{ inputs.results-type }}
          cp -r $RESULTS_PATH/${{ inputs.results-type }} ../$RESULTS_PATH
        fi
        cd ..
        git config --local user.email ${{ inputs.user-email }}
        git config --local user.name ${{ inputs.user-name }}
        git pull
        git add $RESULTS_PATH
        git commit -am "${{ inputs.commit-message }}"
        git push
      shell: bash
